spring:
  application:
    name: markdown-note-app
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:markdown-note-app
    username: sa
    password: password
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      mode: embedded
      data-locations: classpath:db/data.sql
  h2:
    console:
      enabled: true
      path: /h2-console
  data:
    jdbc:
      dialect: h2